export default {
    avatar: { type: String, default: '' },
    nickname: { type: String, default: '' },
    showUserInfo: { type: Boolean, default: true },
    list: { type: Array, default: () => [] },
    codeSrc: { type: String, default: '' },
    codeTitle: { type: String, default: '' },
    codeTitleColor: { type: String, default: '' },
    showCode: { type: Boolean, default: true },
    loginStatus: { type: Number, default: 1 },
    loginSrc: { type: String, default: '' },
    loginTitle: { type: String, default: '' },
    loginInfo: { type: String, default: '' },
    loginBtnText: { type: String, default: '注册/登录' },
    loginBtnBg: { type: String, default: '' },
};
