/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by vite-plugin-uni-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {};

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    PageNavPageNav: typeof import('./components/page-nav/page-nav.vue')['default']
    PageNav: (typeof import('./components/page-nav/index.vue'))['default'];
  }
}
