/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by vite-plugin-uni-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    PageLayoutPageLayout: typeof import('./components/page-layout/page-layout.vue')['default']
    PageNavPageNav: typeof import('./components/page-nav/page-nav.vue')['default']
    TColorPickerTColorPicker: typeof import('./components/t-color-picker/t-color-picker.vue')['default']
  }
}
