/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by vite-plugin-uni-pages

export interface NavigateToOptions {
  url: "/pages/pc/index" |
       "/pages/mp/index" |
       "/pages/mp/demo-views/price/price" |
       "/pages/mp/demo-views/search/search" |
       "/pages/mp/demo-views/signature/signature";
}
interface RedirectToOptions extends NavigateToOptions {}

export interface SwitchTabOptions {
  
}

type ReLaunchOptions = NavigateToOptions | SwitchTabOptions;

declare interface Uni {
  navigateTo(options: UniNamespace.NavigateToOptions & NavigateToOptions): void;
  redirectTo(options: UniNamespace.RedirectToOptions & RedirectToOptions): void;
  switchTab(options: UniNamespace.SwitchTabOptions & SwitchTabOptions): void;
  reLaunch(options: UniNamespace.ReLaunchOptions & ReLaunchOptions): void;
}
